name: submissions_viewer
dependencies:
  - ipython=7.16.1
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - notebook=6.0.3
  - numpy=1.18.5
  - numpy-base=1.18.5
  - requests=2.24.0
  - setuptools=47.3.1
  - pip:
      - ipython-genutils==0.2.0
      - jupyter-client==6.1.5
      - pickleshare==0.7.5
      - pillow==7.2.0
      - pyzmq==19.0.1
